[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[env]
PYTHONPATH = "/app"
PORT = "8080"

[experimental]
# Force HTTPS
httpsUpgrade = true 